context:
  version: "0.3.0"

package:
  name: spaday-lion
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spaday-lion/spaday_lion-${{ version }}.tar.gz
  sha256: 9a9b0637de8e76c63369a5efd13f831eb279f122bc8738c7b00105b2341b42cc

build:
  number: 0
  noarch: python
  script:
    env:
      SKIP_HATCH_JS: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-js
  run:
    - python >=${{ python_min }}
    - spaday >=0.10.0,<1

tests:
  - python:
      imports:
        - spaday_lion
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Lion components and browser assets for spaday
  homepage: https://github.com/1kbgz/spaday-lion
  repository: https://github.com/1kbgz/spaday-lion

extra:
  recipe-maintainers:
    - timkpaine
